### ISSUE TITLE
Noting happens

### ISSUE THREAD

**Issue by epereza** [oosayeroo/qb-methdelivery#1]
I have added items to qbcore/shared.lua, added images to the inventory, and  in target.ini added the target model. Restarted server, but when i make target with the third eye in the ped, it shows me Meth Head, but when I press, nothing happens.

No errors in F8 console, either in server console

Video demonstrative: https://streamable.com/l434wg

**Comment by oosayeroo** [comment]
Sorry about this. I'm currently at work but will look into this as soon as I can thank youSent from my Galaxy
-------- Original message --------From: epereza ***@***.***> Date: 26/06/2022  23:11  (GMT+00:00) To: oosayeroo/qb-methdelivery ***@***.***> Cc: Subscribed ***@***.***> Subject: [oosayeroo/qb-methdelivery] Noting happens (Issue #1) 
I have added items to qbcore/shared.lua, added images to the inventory, and  in target.ini added the target model. Restarted server, but when i make target with the third eye in the ped, it shows me Meth Head, but when I press, nothing happens.

**Comment by oosayeroo** [comment]
I realised the issue and corrected it. Delete the target model info and replace with the new target model info that I've added to read me. Hope that helps :)

**Comment by oosayeroo** [comment]
Please let me know if it works as I'm not home right now so can't test it

**Comment by epereza** [comment]
Now it's working, thank you
![FiveM_b2612_GTAProcess_6zOP1QkGYD](https://user-images.githubusercontent.com/50680351/175875489-4cbcc8ef-4493-40de-915e-a668f0e62957.png)
